### ISSUE TITLE
Goals do not have issues logged for them

### ISSUE THREAD

**Issue by EvanKnowles** [dagwud/woodlands#1]

**Comment by dagwud** [comment]
But even on Wednesday blue jump Quebec?

**Comment by EvanKnowles** [comment]
I'd swear you had a document somewhere with ideas for the game. But they're not written down as handy issues anywhere for a random contributor (any one of us) to grab and implement (as per your vision, you see.)

**Comment by dagwud** [comment]
Aaah. I see. 
They’re on the project wiki, but yeah I haven’t created stories or anything yet.

If you’re looking for something to grab, perhaps the item carrying? The current code just gives you a random item if you ask the innkeeper, but that was just to get going. The blacksmith idea could also be cool?

**Comment by dagwud** [comment]
https://github.com/dagwud/woodlands/wiki/Gameplay-Overview

**Comment by dagwud** [comment]
Shields and Armor are also partly done - the boring definitions are in place, but you can’t get either yet and I don’t think they’re currently part of the calculations yet

**Comment by dagwud** [comment]
Done
