### ISSUE TITLE
Replace permadeath with a diminished fighting mode

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#100]
Perhaps a new status for recovering from injuries?

For 6 hours:
Strength -30%
Agility -30%
This should affect potency of attacks and order in battles

After that, back to normal

**Comment by dagwud** [comment]
New status won’t work; it can’t stack with (eg) resting

**Comment by EvanKnowles** [comment]
You mean, enable big baby mode?

**Comment by dagwud** [comment]
With the introduction of “Ken Mode” (#114) I’m not sure this is still needed

**Comment by dagwud** [comment]
Based on latest market feedback, won’t change this
