### ISSUE TITLE
Need to be able to nest suspendable commands

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#101]
To do cool stuff like spells with timers

**Comment by dagwud** [comment]
Done, needs a verification from @EvanKnowles that it does what he needs. Then remove the sample in DoPlayerSetupCmd

**Comment by EvanKnowles** [comment]
Tweaked behaviour in https://github.com/dagwud/woodlands/commit/b64b1ef0cbffce3fb436dedc0fd989a63fda9fe6, seems to be working correctly.
