### ISSUE TITLE
Switching to a character whose party is not in village should make you leave the party

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#120]
Otherwise you end up taking part in battles even though you’re not there

**Comment by EvanKnowles** [comment]
Or just do a message like the "you can't join that party they're not in the village"?

**Comment by dagwud** [comment]
I think that’d be write a frustrating experience, since you wouldn’t be able to do anything until you happen to get the timing right

**Comment by dagwud** [comment]
Fixed
