### ISSUE TITLE
Leaving the deep woods doesn’t end the encounter

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#140]
So you end up with a “nobody wants to fight” message when you’re in the woodlands

**Comment by EvanKnowles** [comment]
This is why I feel `ELocation` should define this kinda thing - code is a bit scattered.

**Comment by dagwud** [comment]
Yeah, I’m starting to feel that too. I’m not getting the ratio of new features to refactor right, and it’s starting to show.

Whoever gets to it first, let’s do that refactor and see how it comes out

**Comment by EvanKnowles** [comment]
It wasn't a config muck-up, just a general bug.
