### ISSUE TITLE
Need /emote command

### ISSUE THREAD

**Issue by EvanKnowles** [dagwud/woodlands#144]
Like say, but without the says, to produce richer interactions. Emote should probably just be in the current room though.

**Comment by dagwud** [comment]
Like where you’re going with this. How do you imagine it looking to players?

To scope creep your scope creep... how about a /taunt too?

**Comment by EvanKnowles** [comment]
There’s a pretty standard emote in most MUDs, like that ;)

Thanks,
Evan

**Comment by dagwud** [comment]
Would they be inidivual slash commands? /laugh, /beg, etc? We wouldn’t be able to add that many to botfather without making the action commands hard to find, I think. We could have them as commands that botfather doesn’t know about, I guess, which means there’d be some trial-and-error to find them. 

Perhaps an inline query? @bot laugh, @bot beg etc? Doesn’t feel very fluid

Or perhaps we intercept emoji and convert them to text?

I don’t think buttons would work... too many options

**Comment by EvanKnowles** [comment]
Kinda like

> _/emote looks at you threatingly._
**COVID-20 looks at you threatingly.**
