### ISSUE TITLE
Blacksmith - cancel crafting weapons breaks

### ISSUE THREAD

**Issue by BergenLarsen** [dagwud/woodlands#147]
Eina. It broke. 

![Screenshot_20200324-124847](https://user-images.githubusercontent.com/47712770/77428502-161f5a00-6dd0-11ea-8a24-50ed7fd36394.png)

**Comment by dagwud** [comment]
Can't reproduce.

Probably because it took me so long to get off my ass and look at this, so it's possibly not an issue any more
