### ISSUE TITLE
Implement Army of Peasants (General)

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#17]
See wiki

**Comment by EvanKnowles** [comment]
Perhaps Army of Pheasants?

**Comment by dagwud** [comment]
Done! Probably my favourite spell.

**Comment by dagwud** [comment]
@EvanKnowles heads up: big refactor.
GameCharacter is now PlayerCharacter
New class heirarchy:
* Fighter
* Creature extends Fighter
* GameCharacter extends Fighter
* PlayerCharacter and NonPlayerCharacter extend GameCharacter

**Comment by EvanKnowles** [comment]
Still has a typo?

Thanks,
Evan

**Comment by dagwud** [comment]
No, it DOESNT :P
