### ISSUE TITLE
Implement Intimidation (Brawler)

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#27]

**Comment by EvanKnowles** [comment]
> Active: ✨Intimidation - decreases enemy Defence Rating by (Nd8)% for 3 rounds, where N is your level (max 10)

Enemy defence rating seems to be a product of their agility x 10, and some actual defence boost (which I presume could be 0), so there isn't an obvious place to give them a % penalty.

**Comment by dagwud** [comment]
Revised definition:
Active: ✨Intimidation - with your enemy intimidated by your brawn, any attack made for one round will have a boosted chance of dealing a critical hit
