### ISSUE TITLE
More functionality for /look

### ISSUE THREAD

**Issue by EvanKnowles** [dagwud/woodlands#39]

**Comment by EvanKnowles** [comment]
But it doesn't re-print the description :) I found myself typing `look` out of MUD habit.

**Comment by EvanKnowles** [comment]
Any interest in showing other players who're in the room?

**Comment by dagwud** [comment]
Sounds good to me 👍 I also like the idea of offloading the room text - it’s a bit spammy at the moment.

**Comment by EvanKnowles** [comment]
We're going to need a way of tracking which players are in which rooms, for stuff like `look`, `give`, and there was another that escapes me. Looping through the players will probably take too long when there are thousands of them.

**Comment by dagwud** [comment]
Did a basic /look, but none of the extra stuff
