### ISSUE TITLE
Add a “say” command

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#41]
Two options I see...

1. Any message sent to the bot that starts with “say” (eg “say hello”) results in sending that text to whole party, or

2. Anything that’s not recognized as a command is assumed to be dialog, so if you send “hello” it’ll send that to the whole party

Thoughts @EvanKnowles ?

**Comment by EvanKnowles** [comment]
I suspect that 2. will end up in a lot of typos being generated... although most of the game is menu driven really. Perhaps I'm just biased towards 1.

**Comment by dagwud** [comment]
Ok, how bout we spin out 2 and try it and see? Agile styles... ;)

**Comment by dagwud** [comment]
Done as option 2; can tweak later if needed
