### ISSUE TITLE
Weapon/Shield/Trinket drops

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#45]

**Comment by EvanKnowles** [comment]
I assume you mean the creatures drop weapons, but it would be more fun if, on a critical fail, you dropped your weapon.

**Comment by dagwud** [comment]
I lolled

**Comment by EvanKnowles** [comment]
I feel like this is dependent on some sort of room / location inventory system?

**Comment by dagwud** [comment]
I was thinking much simpler - the cmd that decides whether or not an encounter should happen should now choose between doing nothing, generating an encounter, or dropping an item to a random player. And then on creature death, also have a random chance that an item will be dropped.

That’s not particularly exciting though, so also open to ideas around how it should work

**Comment by dagwud** [comment]
We need to fix #85 (stronger weapons) before we do this, otherwise we won’t have enough slots

**Comment by dagwud** [comment]
Done
