### ISSUE TITLE
testJoinParty broken

### ISSUE THREAD

**Issue by EvanKnowles** [dagwud/woodlands#47]
It seems there's a new `PartyRegistry` by the time the second player joins, so they each end up in a different `BetterBetaParty` - suspect because of the `GameRegistry.reset()` call in each initBot

**Comment by dagwud** [comment]
Thanks; that was indeed the root cause.

There’s still one failing test but my train just arrived

**Comment by EvanKnowles** [comment]
I actually found it when I wanted to write a test for my new GiveCmd, and then I got distracted debugging it

Thanks,
Evan
