### ISSUE TITLE
Drunk sober up should queue after previous sober up

### ISSUE THREAD

**Issue by EvanKnowles** [dagwud/woodlands#55]

**Comment by dagwud** [comment]
Not sure if I’m understanding right, but...
There’s a background scheduled command that starts on player creation and sobers you up every x minutes. But I’m fairly sure it’s not restarting after a bounce.

Possibly part of a bigger issue that scheduled commands need to be rescheduled after a bounce

**Comment by EvanKnowles** [comment]
I made Louis join and drink a ton, then his sober-ups all arrived sequentially with no pause in-between.

**Comment by dagwud** [comment]
Can’t reproduce
