### ISSUE TITLE
“Leave items” should allow you to deposit a carried item at the innkeeper, and retrieve it later

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#6]

**Comment by dagwud** [comment]
Doing this will break the “retrieve items” function we currently use for testing.

When doing this, we’ll need to make the player creation also give you one of the weapons you class has a bonus for (the one with the lowest average roll)

**Comment by EvanKnowles** [comment]
Where should we store the items? I'm thinking it may as well just be on the character object.

**Comment by dagwud** [comment]
Perfect 👍

**Comment by dagwud** [comment]
Done:
* stored the items on a new NPC innkeeper attached to each character. That allowed me to reuse the give commands
* did the required work on leave/retrieve items first
* did the implementation for initial items as part of this
