### ISSUE TITLE
Trinket: Cloak of Invisibility

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#70]
Increases chance of being missed during battles

**Comment by dagwud** [comment]
Implement as a WearableItem, most likely

**Comment by EvanKnowles** [comment]
Isn't this closed?

**Comment by dagwud** [comment]
Implemented, Chris is taking it for a spin

**Comment by EvanKnowles** [comment]
Does he look dashing? Or can't you see him at all?

**Comment by dagwud** [comment]
return "Donning the cloak doesn't make you feel any different, but when you look at your arms they seem blurry and hard to focus on. That'll definitely make you harder to hit.";
