### ISSUE TITLE
I don’t think I ever implemented stats boosts on level up

### ISSUE THREAD

**Issue by dagwud** [dagwud/woodlands#86]
Oops. 
Probably needs a data fix too.

**Comment by dagwud** [comment]
Increase of 1 to constitution modifier equates to an increase of 1 to HP maximum

Proficient bonus should be a function of level

Ability Score Improvement

When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature. Some classes have extra levels at which they gain

**Comment by dagwud** [comment]
Increase of 1 to constitution modifier equates to an increase of 1 to HP maximum

Proficient bonus should be a function of level

Ability Score Improvement

When you L4, L8, L12, L16, L19, take 2 points and divide them as you choose between 1 or 2 abilities. Can’t go above 20 though. Some classes have extra levels at which they gain

**Comment by EvanKnowles** [comment]
If they level up and have to make a choice, when do we get them to do that? I expect in the middle of a battle would be annoying.

**Comment by dagwud** [comment]
Indeed. And if they’re not active, I don’t know how that’d play out. 

Probably as an action somewhere in the village? Like a “Level Up” menu item

**Comment by EvanKnowles** [comment]
Yeah, sounds reasonable - didn't that other game also make us do that?

**Comment by dagwud** [comment]
Yeah, and I think I now see why.
It’s a reasonable solution

**Comment by dagwud** [comment]
Implemented; testing

**Comment by dagwud** [comment]
Implemented; testing

**Comment by EvanKnowles** [comment]
I'd say testing is complete? Seems working?

**Comment by dagwud** [comment]
But super happy with it; two of us never got our L4 rewards. Wanna see how the next level up goes first

**Comment by dagwud** [comment]
Working perfectly now
